---
title: Fun with R
author: Naveen
date: '2021-05-25'
slug: fun-with-r
categories:
  - Basics
tags: []
---


## variables and Numbers
```{r}
x <- 1
 y = 2
 3 -> z
 x + y
 y *  z
 y / z
```


## Vectors

```{r}
a <- 0:10 
print(a)

b <- 10:-4


print(b)

class(a)
str(a)

a[c(1,5,8)]

head(a,5)
tail(a,3)

```

## combine operator

```{r}


c <- c(1:5, 10.5, 'red', 'yellow', 'green')
class(c)
str(c)



print(c)

d <- c(1:5, 10.5)

class(d)
str(d)
```

## Sequence operator

```{r}
x<- seq(0, 4*pi, length.out = 200)
y= sin(x)

plot(x,y)

```

## Dropping missing values and summarizing values

```{r}


a<-c(3,-2,4,NA,-1,8,-4,9,NA, 11,3,8,NA)

a[!is.na(a)]

a <-c(2,3,-1,3,5,2,-3,1)

sum(a[a>0])

cat("The sum of positive value",sum(a[a>0]) )

```

## Matrix

```{r}

m1 <- matrix(1:12, ncol =4, byrow = TRUE)
m1


m2 <- matrix(1:12, nrow =4)

m2
```

## Accessing Matrix Element

```{r}

m1 <- matrix(1:20, ncol = 4)
m1[c(3,5), c(2,4)]


```


## Data Frame

```{r}

df <- data.frame(

gender = c("Male", "Male","Female"),

height = c(152, 171.5, 165),

weight = c(81,93, 78),

age =c(42,38,26),

row.names=c('Ally','Belinda','Alfred')

)

df

df$gender
df[df$gender == "Male"]



```

